package com.tumipay.microservice.infrastructure.adapter.output.persistence.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * ProviderIntegrationTransactionEntity
 * <p>
 * Entity representing the tp_payment_adapter_transaction table.
 * Stores the normalized payment transaction processed by the Payment Adapter.
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT STANDARDS AND PROCEDURE
 * AND IS PROTECTED BY INTELLECTUAL PROPERTY AND COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 7/03/2026
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString(callSuper = false)
@Table("tp_provider_transaction")
public class ProviderTransactionEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = -8555744880770987231L;

    /**
     * Primary key identifier of the transaction record.
     */
    @Id
    @Column("pt_id")
    private Long id;

    /**
     * Universally unique identifier of the adapter transaction record.
     */
    @Column("pt_uuid")
    private String uuid;

    /**
     * Unique transaction identifier generated by the TumiPay Gateway.
     */
    @Column("pt_transaction_id")
    private String transactionId;

    /**
     * Reference ID for the transaction, used for correlating related transactions in TumiPay Gateway.
     */
    @Column("pt_reference_id")
    private String referenceId;

    /**
     * Type of transaction (PAYIN or PAYOUT).
     */
    @Column("pt_transaction_type")
    private String transactionType;

    /**
     * Payment method used in the transaction (CARD, PSE, TRANSFER, etc.).
     */
    @Column("pt_payment_method")
    private String paymentMethod;

    /**
     * Code identifying the payment provider used to process the transaction.
     */
    @Column("pt_adapter_provider_code")
    private String adapterProviderCode;

    /**
     * Identifier assigned to the transaction by the payment provider.
     */
    @Column("pt_provider_transaction_id")
    private String providerTransactionId;

    /**
     * Reference ID provided by the payment provider for reconciliation purposes.
     */
    @Column("pt_provider_reference_id")
    private String providerReferenceId;

    /**
     * Idempotency key used to ensure idempotent processing of the transaction.
     */
    @Column("pt_idempotency_key")
    private String idempotencyKey;

    /**
     * Current status of the transaction (PENDING, APPROVED, FAILED, etc.).
     */
    @Column("pt_status")
    private String status;

    /**
     * Monetary value of the transaction.
     */
    @Column("pt_amount")
    private Long amount;

    /**
     * Currency code of the transaction amount (ISO 4217).
     */
    @Column("pt_currency")
    private String currency;

    /**
     * Error code returned by the provider if the transaction failed.
     */
    @Column("pt_error_code")
    private String errorCode;

    /**
     * Error message describing the reason for failure.
     */
    @Column("pt_error_message")
    private String errorMessage;

    /**
     * Timestamp indicating when the provider processed the transaction.
     */
    @Column("pt_provider_processed_at")
    private Instant providerProcessedAt;

    /**
     * Additional normalized payment data stored in JSON format.
     */
    @Column("pt_metadata")
    private String metadata;

    /**
     * Timestamp indicating when the transaction record was created.
     */
    @Column("pt_created_at")
    private Instant createdAt;

    /**
     * Timestamp indicating the last update time of the transaction record.
     */
    @Column("pt_updated_at")
    private Instant updatedAt;
}

