apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.name }}-app-secrets"
  annotations:
    external-secrets.io/secret-type: Opaque
    external-secrets.io/last-updated-for: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
spec: 
  refreshInterval: 10s
  secretStoreRef: 
    name: default
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "{{ .Values.awsSecretName }}"