# Embedded Server configuration
server:
    port: ${ENV_MS_SERVER_PORT:8000}
    compression:
        enabled: true
        min-response-size: 1KB

spring:
    config:
        import: optional:file:.env[.properties]