package com.tumipay.microservice.shared.util;

import lombok.experimental.UtilityClass;

/**
 * CommonStringUtil
 * <p>
 * Utility class that centralizes common validation and defaulting operations
 * for {@link String} and {@link CharSequence} values within the microservice layer.
 * <p>
 * This component provides null-safe helpers for:
 * <ul>
 *     <li>Blank validation (null, empty, or whitespace-only)</li>
 *     <li>Empty validation (null or length = 0)</li>
 *     <li>Default value resolution for empty sequences</li>
 * </ul>
 * <p>
 * Design considerations:
 * <ul>
 *     <li>Annotated with {@link UtilityClass} to enforce static-only usage.</li>
 *     <li>No instantiation allowed (implicit private constructor generated by Lombok).</li>
 *     <li>Stateless and thread-safe by design.</li>
 *     <li>Optimized for defensive programming patterns in DTO validation,
 *     request preprocessing, and business rule enforcement.</li>
 * </ul>
 * <p>
 * Important behavioral notes:
 * <ul>
 *     <li>{@code isBlank} treats whitespace-only strings as blank.</li>
 *     <li>{@code isEmpty} does NOT trim whitespace.</li>
 *     <li>{@code defaultIfEmpty} only evaluates structural emptiness, not blankness.</li>
 * </ul>
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT
 * STANDARDS AND PROCEDURE AND IS PROTECTED BY INTELLECTUAL PROPERTY AND
 * COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @author luisb
 * @since 6/01/2026
 */
@UtilityClass
public class CommonStringUtils {

    /**
     * Determines whether a {@link String} is not blank.
     * <p>
     * A value is considered <b>not blank</b> if:
     * <ul>
     *     <li>It is not {@code null}</li>
     *     <li>It contains at least one non-whitespace character</li>
     * </ul>
     * <p>
     * Examples:
     * <pre>
     * isNotBlank(null)      = false
     * isNotBlank("")        = false
     * isNotBlank("   ")     = false
     * isNotBlank("abc")     = true
     * </pre>
     *
     * @param value the string to evaluate
     * @return {@code true} if the value is not null and contains
     * at least one non-whitespace character; {@code false} otherwise.
     */
    public static boolean isNotBlank(String value) {
        return value != null && !value.isBlank();
    }

    /**
     * Determines whether a {@link String} is blank.
     * <p>
     * A value is considered <b>blank</b> if:
     * <ul>
     *     <li>It is {@code null}</li>
     *     <li>It is empty ({@code ""})</li>
     *     <li>It contains only whitespace characters</li>
     * </ul>
     * <p>
     * This method internally relies on {@link String#isBlank()}.
     * <p>
     * Examples:
     * <pre>
     * isBlank(null)      = true
     * isBlank("")        = true
     * isBlank("   ")     = true
     * isBlank("abc")     = false
     * </pre>
     *
     * @param value the string to evaluate
     * @return {@code true} if the value is null or blank;
     * {@code false} otherwise.
     */
    public static boolean isBlank(String value) {
        return value == null || value.isBlank();
    }

    /**
     * Returns a default value if the provided {@link CharSequence}
     * is empty (null or length = 0).
     * <p>
     * Important:
     * <ul>
     *     <li>This method evaluates structural emptiness only.</li>
     *     <li>Whitespace-only values (e.g., {@code "   "}) are NOT considered empty.</li>
     * </ul>
     * <p>
     * Example:
     * <pre>
     * defaultIfEmpty(null, "default")  = "default"
     * defaultIfEmpty("", "default")    = "default"
     * defaultIfEmpty("abc", "default") = "abc"
     * </pre>
     *
     * @param value        the original value to evaluate
     * @param defaultValue the fallback value to return if {@code value} is empty
     * @param <T>          a type extending {@link CharSequence}
     * @return {@code defaultValue} if {@code value} is empty;
     * otherwise the original {@code value}.
     */
    public static <T extends CharSequence> T defaultIfEmpty(final T value, final T defaultValue) {
        return isEmpty(value) ? defaultValue : value;
    }

    /**
     * Determines whether a {@link CharSequence} is empty.
     * <p>
     * A value is considered empty if:
     * <ul>
     *     <li>It is {@code null}</li>
     *     <li>Its length is zero</li>
     * </ul>
     * <p>
     * This method does NOT trim or evaluate whitespace content.
     * <p>
     * Examples:
     * <pre>
     * isEmpty(null) = true
     * isEmpty("") = true
     * isEmpty(" ") = false
     * isEmpty("abc") = false
     * </pre>
     *
     * @param value the sequence to evaluate
     * @return {@code true} if null or length equals zero;
     * {@code false} otherwise.
     */
    public static boolean isEmpty(final CharSequence value) {
        return value == null || value.isEmpty();
    }

    /**
     * Determines whether a {@link String} is not blank.
     * <p>
     * A value is considered <b>not blank</b> if:
     * <ul>
     *     <li>It is not {@code null}</li>
     *     <li>It contains at least one non-whitespace character</li>
     * </ul>
     * <p>
     * Examples:
     * <pre>
     * isNotEmpty(null)      = false
     * isNotEmpty("")        = false
     * isNotEmpty("   ")     = false
     * isNotEmpty("abc")     = true
     * </pre>
     *
     * @param value the string to evaluate
     * @return {@code true} if the value is not null and contains
     * at least one non-whitespace character; {@code false} otherwise.
     */
    public static boolean isNotEmpty(String value) {
        return value != null && !value.isEmpty();
    }

    /**
     * Returns a safely truncated version of the given {@link String},
     * limited to {@code maxLength} characters.
     * <p>
     * If {@code value} is {@code null}, the {@code defaultValue} is returned instead.
     * If {@code value} is shorter than or equal to {@code maxLength}, it is returned as-is.
     * <p>
     * Examples:
     * <pre>
     * truncate(null, 500, "N/A")         = "N/A"
     * truncate("hello", 500, "N/A")      = "hello"
     * truncate("hello world", 5, "N/A")  = "hello"
     * </pre>
     *
     * @param value        the string to truncate; may be {@code null}
     * @param maxLength    the maximum number of characters to keep (must be &gt;= 0)
     * @param defaultValue the fallback value to return when {@code value} is {@code null}
     * @return the truncated string, or {@code defaultValue} if {@code value} is {@code null}
     */
    public static String truncate(final String value, final int maxLength, final String defaultValue) {
        if (value == null) {
            return defaultValue;
        }
        return value.substring(0, Math.min(value.length(), maxLength));
    }

    /**
     * Returns {@code value} if it is not {@code null}; otherwise returns {@code defaultValue}.
     * <p>
     * Examples:
     * <pre>
     * defaultIfNull(null, "FALLBACK")  = "FALLBACK"
     * defaultIfNull("", "FALLBACK")    = ""
     * defaultIfNull("abc", "FALLBACK") = "abc"
     * </pre>
     *
     * @param value        the string to evaluate; may be {@code null}
     * @param defaultValue the fallback value to return when {@code value} is {@code null}
     * @return {@code value} if not {@code null}; {@code defaultValue} otherwise
     */
    public static String defaultIfNull(final String value, final String defaultValue) {
        return value != null ? value : defaultValue;
    }

    /**
     * Returns {@code value} if it is not {@code null}; otherwise returns {@code defaultValue}.
     * <p>
     * Examples:
     * <pre>
     * defaultIfNull(null, "FALLBACK")  = "FALLBACK"
     * defaultIfNull("", "FALLBACK")    = ""
     * defaultIfNull("abc", "FALLBACK") = "abc"
     * </pre>
     *
     * @param value the string to evaluate; may be {@code null}
     * @return {@code value} if not {@code null}; {@code defaultValue} otherwise
     */
    public static String defaultBlankIfNull(final String value) {
        return value != null ? value : "";
    }
}
