CREATE TABLE IF NOT EXISTS tp_cobre_counterparty (
	cc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cc_uuid VARCHAR(36) NOT NULL,
	cc_cobre_id VARCHAR(100),
	cc_geo VARCHAR(10) NOT NULL,
	cc_type VARCHAR(50) NOT NULL,
	cc_alias VARCHAR(255),
	cc_bank_code VARCHAR(50) NOT NULL,
	cc_account_number VARCHAR(100) NOT NULL,
	cc_document_number VARCHAR(100),
	cc_status VARCHAR(50) NOT NULL,
	cc_error_code VARCHAR(100),
	cc_error_message VARCHAR(4000),
	cc_metadata VARCHAR,
	cc_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	cc_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cc_uuid
	ON tp_cobre_counterparty (cc_uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cc_cobre_id
	ON tp_cobre_counterparty (cc_cobre_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cc_geo_type_document
	ON tp_cobre_counterparty (cc_geo, cc_type, cc_document_number);

CREATE INDEX IF NOT EXISTS idx_cc_account_lookup
	ON tp_cobre_counterparty (cc_geo, cc_type, cc_document_number);

CREATE INDEX IF NOT EXISTS idx_cc_document_number
	ON tp_cobre_counterparty (cc_document_number);

CREATE INDEX IF NOT EXISTS idx_cc_status
	ON tp_cobre_counterparty (cc_status);

CREATE INDEX IF NOT EXISTS idx_cc_created_at
	ON tp_cobre_counterparty (cc_created_at);

CREATE INDEX IF NOT EXISTS idx_cc_geo_account
	ON tp_cobre_counterparty (cc_geo, cc_account_number);

