CREATE TABLE IF NOT EXISTS tp_provider_transaction (
    pt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pt_uuid VARCHAR(36) NOT NULL,
    pt_transaction_id VARCHAR(100) NOT NULL,
    pt_reference_id VARCHAR(100) NOT NULL,
    pt_transaction_type VARCHAR(50) NOT NULL,
    pt_payment_method VARCHAR(50) NOT NULL,
    pt_adapter_provider_code VARCHAR(100) NOT NULL,
    pt_provider_transaction_id VARCHAR(100),
    pt_provider_reference_id VARCHAR(100),
    pt_idempotency_key VARCHAR(100) NOT NULL,
    pt_status VARCHAR(50) NOT NULL,
    pt_amount NUMERIC(18,2) NOT NULL,
    pt_currency VARCHAR(3) NOT NULL,
    pt_error_code VARCHAR(100),
    pt_error_message VARCHAR(4000),
    pt_provider_processed_at TIMESTAMP,
    pt_metadata VARCHAR,
    pt_created_at TIMESTAMP NOT NULL,
    pt_updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pt_uuid
    ON tp_provider_transaction (pt_uuid);

CREATE INDEX IF NOT EXISTS idx_pt_transaction_id
    ON tp_provider_transaction (pt_transaction_id);

CREATE INDEX IF NOT EXISTS idx_pt_provider_transaction_id
    ON tp_provider_transaction (pt_provider_transaction_id);

CREATE INDEX IF NOT EXISTS idx_pt_idempotency_key
    ON tp_provider_transaction (pt_idempotency_key);

CREATE INDEX IF NOT EXISTS idx_pt_status
    ON tp_provider_transaction (pt_status);

CREATE INDEX IF NOT EXISTS idx_pt_created_at
    ON tp_provider_transaction (pt_created_at);

