CREATE TABLE IF NOT EXISTS tp_provider_integration_log (
    pil_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pil_uuid VARCHAR(36) NOT NULL,
    pil_transaction_id VARCHAR(100) NOT NULL,
    pil_reference_id VARCHAR(100) NOT NULL,
    pil_provider_transaction_id VARCHAR(100),
    pil_provider_reference_id VARCHAR(100),
    pil_transaction_type VARCHAR(50) NOT NULL,
    pil_payment_method VARCHAR(50) NOT NULL,
    pil_idempotency_key VARCHAR(100) NOT NULL,
    pil_adapter_provider_code VARCHAR(100) NOT NULL,
    pil_http_method VARCHAR(10),
    pil_provider_endpoint VARCHAR(100),
    pil_request_payload VARCHAR,
    pil_response_payload VARCHAR,
    pil_http_status INTEGER,
    pil_provider_latency_ms INTEGER,
    pil_success BOOLEAN,
    pil_error_code VARCHAR(100),
    pil_error_message VARCHAR(4000),
    pil_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pil_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pil_uuid
    ON tp_provider_integration_log (pil_uuid);

CREATE INDEX IF NOT EXISTS idx_pil_transaction_id
    ON tp_provider_integration_log (pil_transaction_id);

CREATE INDEX IF NOT EXISTS idx_pil_provider_transaction_id
    ON tp_provider_integration_log (pil_provider_transaction_id);

CREATE INDEX IF NOT EXISTS idx_pil_idempotency_key
    ON tp_provider_integration_log (pil_idempotency_key);

CREATE INDEX IF NOT EXISTS idx_pil_created_at
    ON tp_provider_integration_log (pil_created_at);


