CREATE TABLE IF NOT EXISTS tp_provider_webhook_event (
    pwe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pwe_uuid UUID NOT NULL,
    pwe_adapter_provider_code VARCHAR(50) NOT NULL,
    pwe_event_type VARCHAR(100) NOT NULL,
    pwe_external_event_id VARCHAR(255),
    pwe_idempotency_key VARCHAR(255),
    pwe_processing_status VARCHAR(50) NOT NULL,
    pwe_error_code VARCHAR(100),
    pwe_retry_count INTEGER DEFAULT 0 NOT NULL,
    pwe_last_error VARCHAR(500),
    pwe_event_request VARCHAR NOT NULL,
    pwe_received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pwe_processed_at TIMESTAMP,
    pwe_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pwe_claimed_by VARCHAR(100),
    pwe_claimed_at TIMESTAMP,
    pwe_next_retry_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pwe_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tp_provider_webhook_event_uuid UNIQUE (pwe_uuid)
);

CREATE INDEX IF NOT EXISTS idx_pwe_adapter_provider_code
    ON tp_provider_webhook_event (pwe_adapter_provider_code);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_status
    ON tp_provider_webhook_event (pwe_processing_status);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_event_type
    ON tp_provider_webhook_event (pwe_event_type);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_received
    ON tp_provider_webhook_event (pwe_received_at);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_external_event
    ON tp_provider_webhook_event (pwe_external_event_id);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_idempotency
    ON tp_provider_webhook_event (pwe_idempotency_key);

CREATE INDEX IF NOT EXISTS idx_tp_provider_webhook_event_error_code
    ON tp_provider_webhook_event (pwe_error_code);

CREATE INDEX IF NOT EXISTS idx_pwe_worker_pending
    ON tp_provider_webhook_event (pwe_processing_status, pwe_next_retry_at, pwe_created_at);

CREATE INDEX IF NOT EXISTS idx_pwe_worker_claimed
    ON tp_provider_webhook_event (pwe_claimed_at);


