CREATE TABLE IF NOT EXISTS tp_provider_webhook_event_history (
    pweh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pweh_pwe_id BIGINT NOT NULL,
    pweh_pwe_uuid UUID NOT NULL,
    pweh_event_type VARCHAR(100) NOT NULL,
    pweh_old_status VARCHAR(50),
    pweh_new_status VARCHAR(50) NOT NULL,
    pweh_error_code VARCHAR(100),
    pweh_retry_count INTEGER NOT NULL DEFAULT 0,
    pweh_claimed_by VARCHAR(100),
    pweh_changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pweh_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tp_provider_webhook_event_history_pweh_pwe_id_tp_provider_webhook_event
        FOREIGN KEY (pweh_pwe_id)
            REFERENCES tp_provider_webhook_event (pwe_id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pweh_pwe_id
    ON tp_provider_webhook_event_history (pweh_pwe_id);

CREATE INDEX IF NOT EXISTS idx_pweh_status
    ON tp_provider_webhook_event_history (pweh_new_status);

CREATE INDEX IF NOT EXISTS idx_pweh_changed_at
    ON tp_provider_webhook_event_history (pweh_changed_at);

