package com.tumipay.microservice.infrastructure.component.handler;

import com.tumipay.microservice.infrastructure.component.dto.BaseApiResponse;
import com.tumipay.microservice.infrastructure.component.enums.BaseResponseEnum;
import com.tumipay.microservice.shared.dto.ValidationError;
import com.tumipay.microservice.shared.exception.BusinessException;
import com.tumipay.microservice.shared.exception.ValidationException;
import lombok.extern.log4j.Log4j2;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.bind.support.WebExchangeBindException;
import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException;
import org.springframework.web.server.ServerWebInputException;

import java.util.List;
import java.util.stream.Collectors;

/**
 * BaseGlobalExceptionHandler
 * <p>
 * Global exception handler component for REST controllers.
 * <p>
 * This class centralizes exception management across all controllers
 * within the Spring Boot application using {@link RestControllerAdvice}.
 * It ensures consistent API response formatting based on {@link BaseApiResponse}
 * and enforces standardized error structures aligned with TumiPay's
 * microservice architecture guidelines.
 *
 * <p>
 * The handler provides structured responses for:
 * <ul>
 *     <li>Bean validation errors triggered by {@code @Valid}</li>
 *     <li>Custom validation exceptions</li>
 *     <li>Business rule violations</li>
 *     <li>Parameter type mismatches</li>
 *     <li>Unhandled system exceptions</li>
 * </ul>
 *
 * <p>
 * All responses generated by this component:
 * <ul>
 *     <li>Return JSON format (application/json)</li>
 *     <li>Use a unified response wrapper ({@link BaseApiResponse})</li>
 *     <li>Expose standardized error codes</li>
 *     <li>Never leak internal stack traces to clients</li>
 * </ul>
 *
 * <p>
 * This design guarantees:
 * <ul>
 *     <li>Consistency across all microservices</li>
 *     <li>Separation of concerns (controller vs. error management)</li>
 *     <li>Improved API consumer experience</li>
 *     <li>Secure error handling</li>
 * </ul>
 *
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT
 * STANDARDS AND PROCEDURE AND IS PROTECTED BY INTELLECTUAL PROPERTY AND
 * COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 27/12/2025
 */
@Log4j2
@RestControllerAdvice
public class BaseGlobalExceptionHandler {

    private static final String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";

    /**
     * Handles validation errors triggered by Bean Validation annotations
     * such as {@code @NotNull}, {@code @NotBlank}, {@code @Size}, etc.
     * <p>
     * This method intercepts {@link MethodArgumentNotValidException}
     * thrown when a request body annotated with {@code @Valid}
     * fails validation.
     * <p>
     * Behavior:
     * <ul>
     *     <li>Extracts field-level validation errors</li>
     *     <li>Maps them into {@link ValidationError} DTO objects</li>
     *     <li>Wraps them inside a {@link BaseApiResponse}</li>
     *     <li>Returns HTTP 400 (BAD_REQUEST)</li>
     * </ul>
     *
     * @param ex exception containing validation binding errors
     * @return standardized API response with validation details
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<Object> handleBeanValidation(MethodArgumentNotValidException ex) {

        log.error("Error handleBeanValidation handler, validation failed: {}", ex.getMessage());
        final List<ValidationError> errors = ex.getBindingResult()
            .getFieldErrors()
            .stream()
            .map(error ->
                new ValidationError(
                    error.getField(),
                    error.getDefaultMessage()
                )
            )
            .collect(Collectors.toList());

        return buildResponse(BaseApiResponse.<List<ValidationError>>builder()
                .code("VALIDATION_ERROR")
                .status("ERROR")
                .message("Validation failed")
                .data(errors)
                .build(),
            HttpStatus.BAD_REQUEST
        );
    }

    /**
     * Handles custom application-level validation exceptions.
     * <p>
     * Triggered when business-layer validation rules explicitly
     * throw {@link ValidationException}.
     * <p>
     * Behavior:
     * <ul>
     *     <li>Uses the error code provided by the exception</li>
     *     <li>Propagates the validation error list</li>
     *     <li>Returns HTTP 400 (BAD_REQUEST)</li>
     * </ul>
     *
     * @param ex custom validation exception
     * @return standardized API response with validation errors
     */
    @ExceptionHandler(ValidationException.class)
    public ResponseEntity<Object> handleValidationException(ValidationException ex) {

        log.error("Error ValidationException handler, validation failed: {}", ex.getMessage());
        final BaseApiResponse<?> response = BaseApiResponse.builder()
            .code(ex.getCode())
            .status("ERROR")
            .message(ex.getMessage())
            .data(ex.getErrors())
            .build();

        return buildResponse(response, HttpStatus.BAD_REQUEST);
    }

    /**
     * Handles business rule violations.
     * <p>
     * Triggered when application business logic throws
     * {@link BusinessException}.
     * <p>
     * Business exceptions represent controlled functional errors
     * (e.g., insufficient balance, invalid state transitions, etc.)
     * and are not considered system failures.
     * <p>
     * Returns HTTP 400 (BAD_REQUEST).
     *
     * @param ex business exception
     * @return standardized API response containing business error information
     */
    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<Object> handleBusinessException(BusinessException ex) {

        log.error("Error BusinessException handler, error: {}", ex.getMessage());
        final BaseApiResponse<?> response = BaseApiResponse.builder()
            .code(ex.getCode())
            .status("ERROR")
            .message(ex.getMessage())
            .build();

        final HttpStatus status = RESOURCE_NOT_FOUND.equals(ex.getCode())
            ? HttpStatus.NOT_FOUND
            : HttpStatus.BAD_REQUEST;

        return buildResponse(response, status);
    }

    /**
     * Handles parameter type mismatch errors.
     * <p>
     * Triggered when a request parameter cannot be converted
     * to the required method argument type (e.g., passing
     * a String where an Integer is expected).
     * <p>
     * Returns HTTP 400 (BAD_REQUEST).
     *
     * @param ex type mismatch exception
     * @return standardized API response indicating invalid parameter type
     */
    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    public ResponseEntity<Object> handleTypeMismatch(MethodArgumentTypeMismatchException ex) {

        log.error("Error MethodArgumentTypeMismatchException handler, error: {}", ex.getMessage());
        return buildResponse(BaseApiResponse.builder()
                .code("TYPE_MISMATCH")
                .status("ERROR")
                .message("Invalid parameter type")
                .build(),
            HttpStatus.BAD_REQUEST
        );
    }

    /**
     * Handles errors related to malformed request bodies.
     * <p>
     * Triggered when the request body cannot be parsed (e.g., invalid JSON syntax).
     * <p>
     * Returns HTTP 400 (BAD_REQUEST) with a message indicating the parsing issue.
     *
     * @param ex web input exception containing parsing error details
     * @return standardized API response indicating malformed request body
     */
    @ExceptionHandler(ServerWebInputException.class)
    public ResponseEntity<Object> handleWebInputException(ServerWebInputException ex) {

        log.error("Request parsing error: {}", ex.getMessage());
        String message = getMalformedJsonMessage(ex);

        return buildResponse(
            BaseApiResponse.builder()
                .code("INVALID_REQUEST_BODY")
                .status("ERROR")
                .message(message)
                .build(),
            HttpStatus.BAD_REQUEST
        );
    }

    private String getMalformedJsonMessage(ServerWebInputException ex) {
        Throwable cause = ex.getCause();
        if (cause instanceof com.fasterxml.jackson.core.JsonParseException) {
            return "Malformed JSON: syntax error in request body";
        } else if (cause instanceof org.springframework.core.codec.DecodingException) {
            return "Invalid request structure or field types";
        }
        return "Invalid request body";
    }

    /**
     * Handles all uncaught exceptions.
     *
     * <p>
     * Acts as a fallback mechanism for unexpected runtime errors.
     * Prevents stack traces or internal implementation details
     * from being exposed to API consumers.
     *
     * <p>
     * Uses {@link BaseResponseEnum#INTERNAL_ERROR_RESPONSE}
     * as the standardized internal error reference.
     *
     * <p>
     * Returns HTTP 500 (INTERNAL_SERVER_ERROR).
     *
     * @param ex unexpected exception
     * @return standardized API response indicating internal server error
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<Object> handleAllExceptions(Exception ex) {

        log.error("Error Exception handler, error: {}", ex.getMessage());
        final BaseResponseEnum responseEnum = BaseResponseEnum.INTERNAL_ERROR_RESPONSE;

        return buildResponse(BaseApiResponse.builder()
                .code(responseEnum.getCode())
                .status(responseEnum.getStatus())
                .message(ex.getMessage())
                .build(),
            HttpStatus.INTERNAL_SERVER_ERROR
        );
    }

    /**
     * Handles validation errors in reactive contexts.
     * <p>
     * Triggered when validation fails in WebFlux controllers
     * using {@code @Valid} on request bodies.
     * <p>
     * Similar to {@link #handleBeanValidation(MethodArgumentNotValidException)},
     * but specifically for reactive applications.
     *
     * @param ex exception containing validation binding errors
     * @return standardized API response with validation details
     */
    @ExceptionHandler(WebExchangeBindException.class)
    public ResponseEntity<Object> handleWebExchangeBindException(WebExchangeBindException ex) {

        log.error("Validation error: {}", ex.getMessage());

        final List<ValidationError> errors = ex.getFieldErrors()
            .stream()
            .map(error -> new ValidationError(
                error.getField(),
                error.getDefaultMessage()
            ))
            .toList();

        return buildResponse(
            BaseApiResponse.<List<ValidationError>>builder()
                .code("VALIDATION_ERROR")
                .status("ERROR")
                .message("Validation failed")
                .data(errors)
                .build(),
            HttpStatus.BAD_REQUEST
        );
    }

    /**
     * Common response builder.
     *
     * <p>
     * Ensures all responses:
     * <ul>
     *     <li>Include HTTP headers</li>
     *     <li>Set Content-Type to application/json</li>
     *     <li>Return consistent {@link ResponseEntity} objects</li>
     * </ul>
     *
     * @param response wrapped API response body
     * @param status   HTTP status to be returned
     * @return configured ResponseEntity with headers and status
     */
    private ResponseEntity<Object> buildResponse(BaseApiResponse<?> response, HttpStatus status) {

        final HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new ResponseEntity<>(response, headers, status);
    }
}
