package com.tumipay.microservice.domain.port.output;

import com.tumipay.microservice.domain.model.transaction.StandardTransactionResult;
import reactor.core.publisher.Mono;

/**
 * IAdapterTransactionRepositoryPort
 * <p>
 * Output port for querying transaction results processed by the adapter.
 * Defines the reactive contract that infrastructure adapters must implement
 * to retrieve persisted {@link StandardTransactionResult} records
 * throughout the lifecycle of a payment transaction.
 * <p>
 * Each query method exposes a different search criterion, allowing the same
 * transaction to be located through its distinct identifiers: the adapter's
 * internal identifier, the TumiPay system identifier, and the external
 * payment provider identifier.
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT STANDARDS AND PROCEDURE
 * AND IS PROTECTED BY INTELLECTUAL PROPERTY AND COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 7/03/2026
 */
public interface IAdapterTransactionRepositoryPort {

    /**
     * Retrieves a transaction result using the adapter's internal identifier.
     * <p>
     * The {@code adapterTransactionId} is generated by the adapter itself and is unique
     * within its context. It represents the primary internal traceability reference.
     *
     * @param adapterTransactionId unique identifier of the transaction assigned by the adapter.
     * @return {@link Mono} emitting the matching {@link StandardTransactionResult},
     *         or empty ({@code Mono.empty()}) if no record is found for that identifier.
     */
    Mono<StandardTransactionResult> findByAdapterTransactionId(String adapterTransactionId);

    /**
     * Retrieves a transaction result using the TumiPay system transaction identifier.
     * <p>
     * The {@code transactionId} corresponds to the transaction identifier in the TumiPay
     * platform, used to correlate the adapter response with the central payment flow.
     *
     * @param transactionId unique identifier of the transaction in the TumiPay system.
     * @return {@link Mono} emitting the matching {@link StandardTransactionResult},
     *         or empty ({@code Mono.empty()}) if no record is associated with that identifier.
     */
    Mono<StandardTransactionResult> findByTransactionId(String transactionId);

    /**
     * Retrieves a transaction result using the identifier assigned by the external
     * payment provider.
     * <p>
     * The {@code providerTransactionId} is the identifier returned by the provider in its
     * response and serves as the traceability reference towards the external system.
     *
     * @param providerTransactionId unique identifier of the transaction in the external provider's system.
     * @return {@link Mono} emitting the matching {@link StandardTransactionResult},
     *         or empty ({@code Mono.empty()}) if no record exists with that provider identifier.
     */
    Mono<StandardTransactionResult> findByProviderTransactionId(String providerTransactionId);
}