package com.tumipay.microservice.domain.port.output;

import com.tumipay.microservice.domain.model.provider.ProviderTransaction;
import reactor.core.publisher.Mono;

/**
 * IProviderTransactionRepositoryPort
 * <p>
 * Output port for persisting and retrieving provider transaction records.
 * Defines the reactive contract that infrastructure adapters must implement
 * to handle the full lifecycle of a {@link ProviderTransaction}: creation, update
 * and retrieval by different search criteria (UUID, idempotency key, TumiPay
 * transaction ID or provider transaction ID).
 * <p>
 * Each record represents a single payment operation processed by the provider adapter,
 * tracking identifiers, amounts, currency, status, payment method and error information
 * for reconciliation and auditing purposes.
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT STANDARDS AND PROCEDURE
 * AND IS PROTECTED BY INTELLECTUAL PROPERTY AND COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 7/03/2026
 */
public interface IProviderTransactionRepositoryPort {

    /**
     * Persists a new provider transaction record in the repository.
     *
     * @param transaction {@link ProviderTransaction} object containing all details
     *                    of the payment operation to be recorded (identifiers, amount,
     *                    currency, type, status, payment method and metadata).
     * @return {@link Mono} emitting the persisted {@link ProviderTransaction} including
     *         fields generated by the infrastructure (e.g. {@code id}, {@code createdAt}).
     */
    Mono<ProviderTransaction> save(ProviderTransaction transaction);

    /**
     * Updates an existing provider transaction record in the repository.
     * <p>
     * Used to reflect changes after the provider processes the operation, such as
     * updates to {@code status}, {@code providerTransactionId}, {@code providerReferenceId},
     * {@code errorCode}, {@code errorMessage} or {@code updatedAt}.
     *
     * @param transaction {@link ProviderTransaction} object with the updated data.
     *                    Must contain the identifier of the record to be modified.
     * @return {@link Mono} emitting the updated {@link ProviderTransaction} as persisted
     *         in the repository.
     */
    Mono<ProviderTransaction> update(ProviderTransaction transaction);

    /**
     * Retrieves a provider transaction record by its universally unique identifier (UUID).
     *
     * @param uuid UUID of the provider transaction assigned by the system.
     * @return {@link Mono} emitting the matching {@link ProviderTransaction},
     *         or empty ({@code Mono.empty()}) if no record exists with that UUID.
     */
    Mono<ProviderTransaction> findByUuid(String uuid);

    /**
     * Retrieves a provider transaction record by its idempotency key.
     * <p>
     * The {@code idempotencyKey} allows verifying whether a transaction for the same
     * operation has already been submitted, preventing duplicate processing.
     *
     * @param idempotencyKey unique idempotency key associated with the transaction.
     * @return {@link Mono} emitting the matching {@link ProviderTransaction},
     *         or empty ({@code Mono.empty()}) if no record exists with that key.
     */
    Mono<ProviderTransaction> findByIdempotencyKey(String idempotencyKey);

    /**
     * Retrieves a provider transaction record using the TumiPay system transaction identifier.
     *
     * @param transactionId unique identifier of the transaction in the TumiPay system.
     * @return {@link Mono} emitting the matching {@link ProviderTransaction},
     *         or empty ({@code Mono.empty()}) if no record is associated with that identifier.
     */
    Mono<ProviderTransaction> findByTransactionId(String transactionId);

    /**
     * Retrieves a provider transaction record using the identifier assigned by the
     * external payment provider.
     *
     * @param providerTransactionId unique identifier of the transaction in the external provider's system.
     * @return {@link Mono} emitting the matching {@link ProviderTransaction},
     *         or empty ({@code Mono.empty()}) if no record exists with that provider identifier.
     */
    Mono<ProviderTransaction> findByProviderTransactionId(String providerTransactionId);
}
