package com.tumipay.microservice.domain.port.output;

import com.tumipay.microservice.domain.model.provider.ProviderIntegrationLog;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * IProviderIntegrationLogRepositoryPort
 * <p>
 * Output port for persisting and retrieving provider integration log records.
 * Defines the reactive contract that infrastructure adapters must implement
 * to handle the full lifecycle of a {@link ProviderIntegrationLog}: creation, update
 * and retrieval by different search criteria (UUID, transaction ID, idempotency key
 * or adapter provider code).
 * <p>
 * Each log entry traces a single HTTP interaction between the adapter and the external
 * payment provider, capturing request/response payloads, status codes, latency and
 * error information for auditing and debugging purposes.
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT STANDARDS AND PROCEDURE
 * AND IS PROTECTED BY INTELLECTUAL PROPERTY AND COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 7/03/2026
 */
public interface IProviderIntegrationLogRepositoryPort {

    /**
     * Persists a new provider integration log entry in the repository.
     * <p>
     * Should be called immediately before the outbound HTTP call to the provider,
     * capturing the initial state: {@code adapterProviderCode}, {@code transactionType},
     * {@code paymentMethod}, {@code providerEndpoint}, {@code httpMethod},
     * {@code requestPayload} and {@code idempotencyKey}.
     *
     * @param integrationLog {@link ProviderIntegrationLog} object containing all details
     *                       of the HTTP interaction to be recorded.
     * @return {@link Mono} emitting the persisted {@link ProviderIntegrationLog} including
     *         fields generated by the infrastructure (e.g. {@code id}, {@code createdAt}).
     */
    Mono<ProviderIntegrationLog> save(ProviderIntegrationLog integrationLog);

    /**
     * Updates an existing provider integration log entry in the repository.
     * <p>
     * Should be called once the provider responds, to complete the record with outcome
     * fields: {@code responsePayload}, {@code httpStatusCode}, {@code providerLatencyMs},
     * {@code success}, {@code providerTransactionId}, {@code providerReferenceId},
     * {@code errorCode}, {@code errorMessage} and {@code updatedAt}.
     *
     * @param integrationLog {@link ProviderIntegrationLog} object with the updated data.
     *                       Must contain the identifier of the record to be modified.
     * @return {@link Mono} emitting the updated {@link ProviderIntegrationLog} as persisted
     *         in the repository.
     */
    Mono<ProviderIntegrationLog> update(ProviderIntegrationLog integrationLog);

    /**
     * Retrieves an integration log entry by its universally unique identifier (UUID).
     *
     * @param uuid UUID of the integration log assigned by the system.
     * @return {@link Mono} emitting the matching {@link ProviderIntegrationLog},
     *         or empty ({@code Mono.empty()}) if no record exists with that UUID.
     */
    Mono<ProviderIntegrationLog> findByUuid(String uuid);

    /**
     * Retrieves the integration log entry associated with the given TumiPay transaction ID.
     * <p>
     * Note: a single transaction may produce multiple log entries across retries.
     * This method is intended for lookups where a 1-to-1 relationship is guaranteed
     * (e.g. by idempotency). Use {@link #findAllByAdapterProviderCode(String)} to
     * retrieve all entries for broader queries.
     *
     * @param transactionId unique identifier of the transaction in the TumiPay system.
     * @return {@link Mono} emitting the matching {@link ProviderIntegrationLog},
     *         or empty ({@code Mono.empty()}) if no record is associated with that transaction.
     */
    Mono<ProviderIntegrationLog> findByTransactionId(String transactionId);

    /**
     * Retrieves an integration log entry by its idempotency key.
     * <p>
     * The {@code idempotencyKey} allows correlating a log entry with the originating
     * request, ensuring only one record is created per unique operation.
     *
     * @param idempotencyKey unique idempotency key associated with the integration log.
     * @return {@link Mono} emitting the matching {@link ProviderIntegrationLog},
     *         or empty ({@code Mono.empty()}) if no record exists with that key.
     */
    Mono<ProviderIntegrationLog> findByIdempotencyKey(String idempotencyKey);

    /**
     * Retrieves all integration log entries recorded for a specific adapter provider code.
     * <p>
     * Useful for auditing, reconciliation and debugging all HTTP interactions
     * performed by a given provider adapter, including retries and failed attempts.
     *
     * @param adapterProviderCode unique code of the payment adapter/provider
     *                            whose log entries should be retrieved.
     * @return {@link Flux} emitting all {@link ProviderIntegrationLog} records associated
     *         with that provider, or an empty stream if none are found.
     */
    Flux<ProviderIntegrationLog> findAllByAdapterProviderCode(String adapterProviderCode);
}
