package com.tumipay.microservice.domain.port.output;

import com.tumipay.microservice.domain.model.webhook.WebhookEvent;
import reactor.core.publisher.Mono;

import java.util.UUID;

/**
 * IProviderWebhookEventRepositoryPort
 * <p>
 * Output port for persisting and retrieving webhook events received from the provider.
 * Defines the reactive contract that infrastructure adapters must implement
 * to handle the complete lifecycle of a {@link WebhookEvent}: creation, update
 * and retrieval by different search criteria.
 * <p>
 * This port is used by the domain to guarantee idempotency in webhook event processing,
 * preventing reprocessing of already handled notifications through validation
 * by {@code idempotencyKey} or {@code externalEventId}.
 * <p>
 * THIS COMPONENT WAS BUILT FOLLOWING TUMIPAY'S APPLICATION DEVELOPMENT STANDARDS AND PROCEDURE
 * AND IS PROTECTED BY INTELLECTUAL PROPERTY AND COPYRIGHT LAWS.
 *
 * @author TumiPay SAS.
 * @since 5/04/2026
 */
public interface IProviderWebhookEventRepositoryPort {

    /**
     * Persists a new webhook event in the repository.
     * <p>
     * Must be called the first time a provider notification is received,
     * before starting its processing.
     *
     * @param webhookEvent {@link WebhookEvent} object containing all event data
     *                     (event type, payload, initial status, etc.).
     * @return {@link Mono} emitting the persisted {@link WebhookEvent} including
     *         fields generated by the infrastructure (e.g. {@code id}, {@code createdAt}).
     */
    Mono<WebhookEvent> save(WebhookEvent webhookEvent);

    /**
     * Updates an existing webhook event in the repository.
     * <p>
     * Used to reflect processing state changes of the event, such as updates
     * to {@code processingStatus}, {@code retryCount}, {@code lastError}
     * or {@code processedAt}.
     *
     * @param webhookEvent {@link WebhookEvent} object with the updated event data.
     *                     Must contain the identifier of the record to be modified.
     * @return {@link Mono} emitting the updated {@link WebhookEvent} as persisted
     *         in the repository.
     */
    Mono<WebhookEvent> update(WebhookEvent webhookEvent);

    /**
     * Retrieves a webhook event by its universally unique identifier (UUID).
     *
     * @param uuid UUID identifier of the webhook event assigned by the system.
     * @return {@link Mono} emitting the matching {@link WebhookEvent},
     *         or empty ({@code Mono.empty()}) if no record exists with that UUID.
     */
    Mono<WebhookEvent> findByUuid(UUID uuid);

    /**
     * Retrieves a webhook event by its idempotency key.
     * <p>
     * The {@code idempotencyKey} allows verifying whether an equivalent event has already
     * been received and processed, thereby preventing duplicate processing.
     *
     * @param idempotencyKey unique idempotency key associated with the webhook event.
     * @return {@link Mono} emitting the matching {@link WebhookEvent},
     *         or empty ({@code Mono.empty()}) if no record exists with that key.
     */
    Mono<WebhookEvent> findByIdempotencyKey(String idempotencyKey);

    /**
     * Retrieves a webhook event by the external identifier assigned by the provider.
     * <p>
     * The {@code externalEventId} is the identifier included by the provider in the
     * event notification and serves as the traceability reference towards the external system.
     *
     * @param externalEventId unique identifier of the event in the external provider's system.
     * @return {@link Mono} emitting the matching {@link WebhookEvent},
     *         or empty ({@code Mono.empty()}) if no record exists with that external identifier.
     */
    Mono<WebhookEvent> findByExternalEventId(String externalEventId);
}
